# Generated by Django 2.2.4 on 2021-05-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210525_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Categoria 1'), ('2', 'Categoria 2'), ('3', 'Categoria 3')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='none.jpg', null=True, upload_to='productos'),
        ),
    ]
