# Generated by Django 2.2.4 on 2021-05-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210526_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, unique=True, upload_to='productos'),
        ),
    ]
