# Generated by Django 2.2.4 on 2021-05-22 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('nivel_usuario', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='El código de Usuario debe ser igual a 1 para clientes.'), django.core.validators.MaxValueValidator(2, message='El código de Usuario debe ser igual a 2 para administradores.')])),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
