# Generated by Django 2.2.4 on 2021-05-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210525_1737'),
        ('logReg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
